#spring:
#  boot:
#    admin:
#      client:
#        enabled: true
#        instance:
#          service-url: http://companydv.starapp.com:8083
#  datasource:
#    url: jdbc:mysql://localhost:3306/star_shipment_db?useSSL=false
#    username: root
#    password: "P@ssw0rd"
#
#server:
#  port: 8083

